name: news_app
description: A new Flutter project with News
publish_to: 'none'
version: 1.2.0-fl

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  get_it: 7.6.4
  dio: 5.4.0
  flutter_bloc: 8.1.3
  provider: 6.1.1
  freezed_annotation: 2.4.1
  cached_network_image: 3.3.0
  intl: 0.18.1
  equatable: 2.0.5
  json_annotation: 4.8.1
  shared_preferences: 2.2.2
  url_launcher: 6.1.14
  fluttertoast: 8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  build_runner: 2.4.7
  freezed: 2.4.5
  json_serializable: 6.7.1

flutter:
  uses-material-design: true
