
on:
  push:
    tags:
      - release-v*

name: Release App
jobs:
  build:
    name: Release App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Export Release Timestamp
        run: echo "APP_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Set up Flutter
        uses: subosito/flutter-action@v1

      - name: Install pub dependencies
        run: flutter pub get

      - name: Run Code Generation
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Android App
        run: flutter build apk --split-per-abi --dart-define=NEWS_API_KEY=${{ secrets.NEWS_API_KEY }} --dart-define=NEWS_BASE_URL=${{ secrets.NEWS_BASE_URL }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.APP_VERSION }}
          release_name: ${{ env.APP_VERSION }}
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
